apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine-volume
  labels:
    name: nginx-alpine-volume
spec:
  containers:
    - name: nginx-alpine-volume
      image: nginx:alpine
      volumeMounts:
        - name: html2
          mountPath: /usr/share/nginx/html
          readOnly: true
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
    - name: html-updater
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        # - while true; do date >> /html/index.html;sleep 3; done
        - while true; do cat /html/index.html; sleep 10s; done
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: html2
          mountPath: /html
          readOnly: true
  volumes:
    - name: html2
      emptyDir: {}
