apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.28.4
      resources:
        limits:
          memory: "64Mi"
          cpu: "10m"
      command:
        - /bin/sh
        - -c
        - sleep 60m
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
