apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - name: server
          mountPath: /usr/share/nginx/html
          # subPath: index.html
          # readOnly: true
    - name: html-logger
      image: alpine
      resources: {}
      command: ["/bin/sh", "-c"]
      args:
        # - while true; do date >> /html/index.html;sleep 3; done
        - while true; do cat /html/index.html; sleep 10s; done
      volumeMounts:
        - name: server
          mountPath: /html
          readOnly: true
  volumes:
    - name: html
      emptyDir: {}
    - name: server
      configMap:
        name: server

# kubectl create -f nginx.pod.yml --save-config (can apply changes if you have this command)
# kubectl describe pod [pod-name] (Very helpful if you wanted to dive deeper in your Pods)
# kubectl apply -f nginx.pod.yml (apply changes to your pods if you --save-config in your kubectl command)
# kubectl exec [pod-name] -it bash (This would be very helpful if you wanted to debug or edit something in your container)
# kubectl edit -f nginx.pod.yml (Live editing your yaml file)
# kubectl delete -f nginx.pod.yml (will delete your pod and your yaml file)
