apiVersion: v1
kind: Pod
metadata:
  name: pod-alpine
spec:
  containers:
    - name: pod-alpine
      image: alpine:3.11.2
      resources:
        limits:
          memory: "64Mi"
          cpu: "10m"
      command:
        - /bin/sh
        - -c
        - apk add --no-cache curl bash && sleep 60m