apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: pod-server1-deployment
  type: NodePort
  ports:
    - targetPort: 80 # the target port that connects to pod
      port: 80
