apiVersion: v1
kind: Pod
metadata:
  name: pod-server2
  labels:
    app: pod-server1
spec:
  containers:
    - name: pod-server1-deployment
      image: nginx:1.19.6-alpine
      resources:
        limits:
          memory: "50Mi"
          cpu: "10m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: index
          mountPath: /tmp/index2.html
          subPath: index2.html
      command: ["/bin/sh", "-c"]
      args:
        [
          "cp /tmp/index2.html /usr/share/nginx/html/index.html; nginx; sleep inf",
        ]
  volumes:
    - name: index
      configMap:
        name: server2
