apiVersion: v1
kind: Pod
metadata:
  name: pod-server1
  labels:
    app: pod-server1
spec:
  containers:
    - name: pod-server1
      image: nginx:1.19.6-alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      volumeMounts:
        - name: index
          mountPath: /tmp/index1.html
          # subPath will turn the folder into a file
          # load only index1.html
          subPath: index1.html
      command: ["/bin/sh", "-c"]
      args:
        [
          "cp /tmp/index1.html /usr/share/nginx/html/index.html; nginx; sleep inf",
        ]
  volumes:
    - name: index
      configMap:
        name: server1
