apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-server1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-server1-deployment
  template:
    metadata:
      labels:
        app: pod-server1-deployment
    spec:
      containers:
        - name: pod-server1-container
          image: nginx:1.19.6-alpine
          resources:
            limits:
              memory: "50Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: index
              mountPath: /tmp/index1.html
              subPath: index1.html
          command: ["/bin/sh", "-c"]
          args:
            [
              "cp /tmp/index1.html /usr/share/nginx/html/index.html; nginx; sleep inf",
            ]
      volumes:
        - name: index
          configMap:
            name: server1
        - name: html
          emptyDir: {}
