apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: LoadBalancer
  selector:
    app: node-app # used to select all pods with the same name select node-app
  ports:
  - port: 80
    targetPort: 8080