apiVersion: v1
kind: Pod
metadata:
  name: private-pod
spec:
  imagePullSecrets:
    # specify the secret that you created so that
    # it pull's from docker private registry
    - name: mydockerhubsecret
  containers:
    - name: main
      image: username/private:tag
