apiVersion: v1
kind: Pod
metadata:
  name: secret-using-env
  labels:
    name: secret-using-env
spec:
  containers:
    - name: secret-using-env
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "10m"
      ports:
        - containerPort: 80
      env:
        - name: SECRET_URL
          valueFrom:
            secretKeyRef:
              name: myapi-url-token
              key: secreturl.txt
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: myapi-url-token
              key: secrettoken.txt
  restartPolicy: Never # instruct pod to restart the container if the container fails to run in your pod.
