apiVersion: v1
kind: Pod
metadata:
  name: secret-using-volume
  labels:
    name: secret-using-volume
spec:
  containers:
    - name: secret-using-volume
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: secretvolume
          mountPath: "/etc/config"
          readOnly: true
      ports:
        - containerPort: 80
  volumes:
    - name: secretvolume
      secret:
        secretName: myapi-url-token
